version: '3'
services:
  zookeeper:
    hostname: zookeeper
    ports:
      - 2181:2181
    image: wurstmeister/zookeeper
    container_name: zookeeper

  kafka:
    hostname: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: >
        fb-event.match-scheduled:1:1,
        fb-event.match-started:1:1,
        fb-event.goal-scored:1:1,
        fb-event.card-received:1:1,
        fb-event.match-finished:1:1,
        fb-event.player-started-career:1:1,
        fb-view.match-score:1:1,
        fb-view.team-ranking:1:1,
        fb-view.player-goals:1:1,
        fb-view.player-cards:1:1,
        fb-view.top-players:1:1,
        fb-connect.public.players:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 999
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    links:
      - zookeeper

  postgres:
    image: debezium/example-postgres:latest
    container_name: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  connect:
    image: debezium/connect:latest
    container_name: connect
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: fb.connect.configs
      OFFSET_STORAGE_TOPIC: fb.connect.offsets

  debezium-ui:
    image: debezium/debezium-ui:latest
    container_name: debezium-ui
    ports:
     - 8084:8080
    links:
     - connect
    environment:
      KAFKA_CONNECT_URIS: http://connect:8083

  football-match:
    container_name: football-match
    ports:
      - 18081:18081
    depends_on:
      - kafka
    build: football-match/
    image: football-match:latest

  football-player:
    container_name: football-player
    ports:
      - 18082:18082
    depends_on:
      - kafka
    build: football-player/
    image: football-player:latest

  football-view-basic:
    container_name: football-view-basic
    ports:
      - 18083:18083
    depends_on:
      - kafka
    build: football-view-basic/
    image: football-view-basic:latest

  football-view-top:
    container_name: football-view-top
    ports:
      - 18084:18084
    depends_on:
      - kafka
    build: football-view-top/
    image: football-view-top:latest

  football-ui:
    container_name: football-ui
    ports:
      - 18080:18080
    depends_on:
      - kafka
    build: football-ui/
    image: football-ui:latest
